services:
  redis:
    image: redis:7.2-alpine
    container_name: financial-assistant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - financial_network

  # Optional: Redis Commander for Redis GUI management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: financial-assistant-redis-ui
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=redis123
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - financial_network
    profiles:
      - tools # Only start with: docker-compose --profile tools up

volumes:
  redis_data:
    driver: local

networks:
  financial_network:
    driver: bridge