# Development-specific overrides
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up

services:
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_LOG_LEVEL=notice
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - finapsis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  finapsis:
    driver: bridge

volumes:
  redis_data: { }