services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    networks:
      - finapsis
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - finapsis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - finapsis
networks:
  finapsis:
    driver: bridge