# Development-specific overrides
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_LOG_LEVEL=notice
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=dev
      - HTTP_PASSWORD=dev123
      - LOG_LEVEL=info
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - finapsis

  redis-cli:
    image: redis:7.2-alpine
    container_name: financial-assistant-redis-cli
    command: redis-cli -h redis -p 6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - finapsis
    profiles:
      - cli # Start with: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml --profile cli up
    stdin_open: true
    tty: true

volumes:
  redis_data: {}