name: Install Docker On VM
on:
  push:
    branches:
      - install-docker-vm
jobs:
  install:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/install-docker-vm'
    environment: prod

    steps:
      - name: Install Docker on Oracle Cloud VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.OCI_HOST }}
          username: opc
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            
            #Install docker & docker compose
            sudo dnf update -y
            sudo dnf -y install dnf-plugins-core curl
            sudo dnf-3 config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
            sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
            sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo systemctl enable --now docker
            sudo systemctl status docker --no-pager
            sudo usermod -aG docker $USER
            newgrp docker
            
            echo "Install successful!"